import Header from "@components/components/Header";
import type { Metadata } from "next";
import { Poppins, Lora  } from "next/font/google";
import "./globals.css";

const PoppinsFont = Poppins({ 
  subsets: ["latin"],
  weight: ['100', '200', '300', '500', '800'],
   variable: '--font-poppins'
});
const LoraFont = Lora({ 
  subsets: ["latin"],
  weight: ['400', '500'],
  variable: '--font-lora',
 
})

export const metadata: Metadata = {
  title: "Josephne_portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${PoppinsFont.variable} ${LoraFont.variable}`}>
        <Header/>
        {children}
      
      </body>
    </html>
  );
}
