import Header from "@components/components/Header";
import type { Metadata } from "next";
import { Poppins, Lora  } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner'

const PoppinsFont = Poppins({ 
  subsets: ["latin"],
  weight: ['100', '200', '300', '500', '800'],
   variable: '--font-poppins'
});
const LoraFont = Lora({ 
  subsets: ["latin"],
  weight: ['400', '500'],
  variable: '--font-lora',
 
})

export const metadata: Metadata = {
  title: "Josephne_portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${PoppinsFont.variable} ${LoraFont.variable}`}>
        <Header/>
        {children}
        <Toaster
          position="top-right"
          richColors 
          toastOptions={{
            duration: 4000,      
            classNames: {                  
              success: 'bg-green-600 text-white',
              error:   'bg-red-600   text-white',
              loading: 'bg-blue-600  text-white',
            },
          }}
        />
      
      </body>
    </html>
  );
}
